
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc-data
  namespace: {{ .Values.namespace }}
spec:
  volumeName: pv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
